FROM corona-school-base

# Copy dependency files, as only changes to them will trigger reinstalls
COPY ./backend-screening/package.json ./package.json
COPY ./backend-screening/yarn.lock ./yarn.lock

# Install Yarn
# RUN curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc

# TODO: Unfortunately the postinstall cannot run at this point. Falling back to npm, see https://github.com/yarnpkg/yarn/issues/4100 
# RUN yarn install

RUN npm install typescript -g
RUN npm install

# Hopefully cache images till this point

# Copy sources
COPY ./backend-screening ./

# Set up environment configuration files
COPY ./dev-env/backend-screening.env ./.env


# TODO: Seperate build / run stage

# Screening Backend
EXPOSE 3001

CMD npm run dev
