FROM node:10

# Copy dependency files, as only changes to them will trigger reinstalls
COPY ./web-screening-admin/package.json ./package.json

# There are some global dependencies:
RUN npm install react-scripts react-app-rewired typescript --global

RUN npm install

# Hopefully cache images till this point

# Copy sources
COPY ./web-screening-admin ./

# Set up environment configuration files
COPY ./dev-env/web-screening-admin.env ./.env



# TODO: Seperate build / run stage

# Admin Web:
EXPOSE 80


CMD npm run dev