FROM node:10

# Copy dependency files, as only changes to them will trigger reinstalls
COPY ./web-screening-app/package.json ./package.json

# There are some global dependencies:
RUN npm install react-scripts react-app-rewired typescript --global

RUN npm install

# Hopefully cache images till this point

# Copy sources
COPY ./web-screening-app/ ./

# Set up environment configuration files
COPY ./dev-env/web-screening-app.env ./.env



# TODO: Seperate build / run stage

# App Web
EXPOSE 80

CMD npm run dev