FROM corona-school-base

# Copy dependency files, as only changes to them will trigger reinstalls
COPY ./backend/package.json  ./package.json
COPY ./backend/package-lock.json ./package-lock.json


# There are some global dependencies:
RUN npm install typescript --global

COPY ./backend/package.json ./
COPY ./backend/package-lock.json ./


RUN npm ci # unfortunately installation has to happen here, as Linux binaries break otherwise (bcrypt native module)

## Copy sources
COPY ./backend  ./

# Set up environment configuration files
COPY ./dev-env/backend.env ./.env

RUN npm run build:clean

# TODO: Seperate build / run stage

# Backend
EXPOSE 5000

CMD npm run web:dev
